# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPlane.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPlaneDialog(object):
    def setupUi(self, addPlaneDialog):
        addPlaneDialog.setObjectName("addPlaneDialog")
        addPlaneDialog.resize(320, 70)
        self.buttons = QtWidgets.QDialogButtonBox(addPlaneDialog)
        self.buttons.setGeometry(QtCore.QRect(90, 30, 221, 41))
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.widget = QtWidgets.QWidget(addPlaneDialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 301, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.planeName = QtWidgets.QLineEdit(self.widget)
        self.planeName.setObjectName("planeName")
        self.horizontalLayout.addWidget(self.planeName)

        self.retranslateUi(addPlaneDialog)
        self.buttons.accepted.connect(addPlaneDialog.accept) # type: ignore
        self.buttons.rejected.connect(addPlaneDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addPlaneDialog)

    def retranslateUi(self, addPlaneDialog):
        _translate = QtCore.QCoreApplication.translate
        addPlaneDialog.setWindowTitle(_translate("addPlaneDialog", "Dialog"))
        self.label.setText(_translate("addPlaneDialog", "Plane Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addPlaneDialog = QtWidgets.QDialog()
    ui = Ui_addPlaneDialog()
    ui.setupUi(addPlaneDialog)
    addPlaneDialog.show()
    sys.exit(app.exec_())
