# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'planeSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_planesSettings(object):
    def setupUi(self, planesSettings):
        planesSettings.setObjectName("planesSettings")
        planesSettings.setWindowModality(QtCore.Qt.NonModal)
        planesSettings.resize(609, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(planesSettings.sizePolicy().hasHeightForWidth())
        planesSettings.setSizePolicy(sizePolicy)
        self.settingsFrame = QtWidgets.QFrame(planesSettings)
        self.settingsFrame.setGeometry(QtCore.QRect(20, 40, 561, 511))
        self.settingsFrame.setObjectName("settingsFrame")
        self.settingsLayout = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.settingsLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsLayout.setSpacing(0)
        self.settingsLayout.setObjectName("settingsLayout")
        self.layoutWidget = QtWidgets.QWidget(planesSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 560, 198, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addPlane = QtWidgets.QPushButton(self.layoutWidget)
        self.addPlane.setObjectName("addPlane")
        self.horizontalLayout_3.addWidget(self.addPlane)
        self.removePlane = QtWidgets.QPushButton(self.layoutWidget)
        self.removePlane.setObjectName("removePlane")
        self.horizontalLayout_3.addWidget(self.removePlane)
        self.layoutWidget1 = QtWidgets.QWidget(planesSettings)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 561, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.simList = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simList.sizePolicy().hasHeightForWidth())
        self.simList.setSizePolicy(sizePolicy)
        self.simList.setObjectName("simList")
        self.horizontalLayout_2.addWidget(self.simList)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.planesList = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.planesList.sizePolicy().hasHeightForWidth())
        self.planesList.setSizePolicy(sizePolicy)
        self.planesList.setObjectName("planesList")
        self.horizontalLayout_2.addWidget(self.planesList)
        self.layoutWidget2 = QtWidgets.QWidget(planesSettings)
        self.layoutWidget2.setGeometry(QtCore.QRect(390, 560, 201, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveBtn = QtWidgets.QPushButton(self.layoutWidget2)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.exit = QtWidgets.QPushButton(self.layoutWidget2)
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)

        self.retranslateUi(planesSettings)
        QtCore.QMetaObject.connectSlotsByName(planesSettings)

    def retranslateUi(self, planesSettings):
        _translate = QtCore.QCoreApplication.translate
        planesSettings.setWindowTitle(_translate("planesSettings", "MainWindow"))
        self.addPlane.setText(_translate("planesSettings", "+ Add Plane"))
        self.removePlane.setText(_translate("planesSettings", "- Remove Plane"))
        self.label.setText(_translate("planesSettings", "Simulator"))
        self.label_2.setText(_translate("planesSettings", "Plane"))
        self.saveBtn.setText(_translate("planesSettings", "Save"))
        self.exit.setText(_translate("planesSettings", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    planesSettings = QtWidgets.QDialog()
    ui = Ui_planesSettings()
    ui.setupUi(planesSettings)
    planesSettings.show()
    sys.exit(app.exec_())
