# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\zTelem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 367)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comportsgroup = QtWidgets.QGroupBox(self.centralwidget)
        self.comportsgroup.setGeometry(QtCore.QRect(410, 10, 121, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comportsgroup.sizePolicy().hasHeightForWidth())
        self.comportsgroup.setSizePolicy(sizePolicy)
        self.comportsgroup.setMinimumSize(QtCore.QSize(0, 5))
        self.comportsgroup.setObjectName("comportsgroup")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.comportsgroup)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 101, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comSelect.setObjectName("comSelect")
        self.verticalLayout_3.addWidget(self.comSelect)
        self.refreshComBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshComBtn.sizePolicy().hasHeightForWidth())
        self.refreshComBtn.setSizePolicy(sizePolicy)
        self.refreshComBtn.setObjectName("refreshComBtn")
        self.verticalLayout_3.addWidget(self.refreshComBtn)
        self.autoConnect = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.autoConnect.setObjectName("autoConnect")
        self.verticalLayout_3.addWidget(self.autoConnect)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.connectBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connectBtn.setObjectName("connectBtn")
        self.verticalLayout_3.addWidget(self.connectBtn)
        self.disconnectBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.disconnectBtn.setEnabled(False)
        self.disconnectBtn.setObjectName("disconnectBtn")
        self.verticalLayout_3.addWidget(self.disconnectBtn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.comportsgroup)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 101, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.status = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.status.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.status.setFont(font)
        self.status.setAutoFillBackground(False)
        self.status.setObjectName("status")
        self.verticalLayout_2.addWidget(self.status)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 261))
        self.groupBox.setObjectName("groupBox")
        self.telemStatus = QtWidgets.QLabel(self.groupBox)
        self.telemStatus.setGeometry(QtCore.QRect(10, 20, 341, 221))
        self.telemStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.telemStatus.setObjectName("telemStatus")
        self.simSettingsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.simSettingsBtn.setGeometry(QtCore.QRect(420, 270, 101, 21))
        self.simSettingsBtn.setObjectName("simSettingsBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comportsgroup.setTitle(_translate("MainWindow", "COM Ports"))
        self.refreshComBtn.setText(_translate("MainWindow", "Refresh"))
        self.autoConnect.setText(_translate("MainWindow", "Auto Connect"))
        self.connectBtn.setText(_translate("MainWindow", "Connect"))
        self.disconnectBtn.setText(_translate("MainWindow", "Disconnect"))
        self.label_2.setText(_translate("MainWindow", "zFSB Status"))
        self.status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:8pt;\">zFSB not connected.</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "DCS Telemetry"))
        self.telemStatus.setText(_translate("MainWindow", "Waiting for telemetry"))
        self.simSettingsBtn.setText(_translate("MainWindow", "Sim Settings"))
